kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: localkindcluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30050
    hostPort: 80
  - containerPort: 30051
    hostPort: 443
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30443
    hostPort: 30443
  - containerPort: 15021
    hostPort: 15021
