version: '3'

includes:
  clienta:
    taskfile: ./ProjectForClientA/Taskfile.yaml
    dir: ./ProjectForClientA
    aliases: [ "a" ]

  clientb:
    taskfile: ./ProjectForClientB/Taskfile.yaml
    dir: ./ProjectForClientB
    aliases: [ "b" ]

tasks:

  full-start:
    desc: "Create the Kind cluster, deploy the Helm chart and expose the service"
    cmds:
    - task create-cluster
    - task upgrade-chart
    silent: false
    aliases: [ "fs" ]

  full-stop:
    desc: "Delete the Helm chart and the Kind cluster"
    cmds:
    - task delete-chart
    - task delete-cluster
    silent: false
    aliases: [ "fstop" ]

  create-cluster:
    desc: "Create the Kind cluster using the PowerShell script"
    cmds:
    - powershell -ExecutionPolicy Bypass -File create-kind-cluster.ps1
    silent: false
    aliases: [ "c" ]

  delete-cluster:
    desc: "Delete the Kind cluster"
    cmds:
    - kind delete cluster --name kind-cluster
    silent: false
    aliases: [ "d" ]

  upgrade-chart:
    desc: "Deploy or upgrade the Helm chart"
    cmds:
    - helm upgrade --install clustergateway ./ClusterGateway  --namespace clustergateway  --create-namespace
    silent: false
    aliases: [ "u" ]

  delete-chart:
    desc: "Delete the namespace where the Helm chart is deployed"
    cmds:
    - helm uninstall clustergateway --namespace clustergateway
    - kubectl delete namespace clustergateway --ignore-not-found
    silent: false
    aliases: [ "dc" ]
