apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-selfsigned-cert
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: "*.localhost"
  dnsNames:
    - "*.localhost"
