---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-aspnetcore-sample
  labels:
    app: aspnetcore-sample
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: aspnetcore-sample
  template:
    metadata:
      labels:
        app: aspnetcore-sample
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: aspnetcore-sample
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
