replicaCount: 1

nginx:
  image: "nginx:latest"

hostName: "hello-world.localhost"

gateway:
  name: "localhost-gateway"
  ns: "istio-ingress"
  host: "*.localhost"

  # either nginx-app-tls or mkcert-tls
  tlsSecretName: "nginx-app-tls"
