replicaCount: 1

nginx:
  image: "nginx:latest"

hostName: "nginx.localhost"

gateway:
  name: "localhost-gateway"
  ns: "istio-ingress"
  host: "*.localhost"

  # either nginx-app-tls or wildcard-localhost-tls
  tlsSecretName: "wildcard-localhost-tls"
