---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-nginx-vs
spec:
  hosts:
    - {{ .Values.virtualService.hostName }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - route:
        - destination:
            host: nginx-app
            port:
              number: 80
