apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-selfsigned-cert
  namespace: istio-ingress
spec:
  secretName: nginx-app-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: "*.localhost"
  dnsNames:
    - "*.localhost"
